### PR TITLE
Check also associated roles for permission

### PR DESCRIPTION
**Pull request by thorsten-l**
Not only direct members of the 'restricted-role' get access, members of associated roles with the 'restricted-access' role gets access also. This leads to much more flexibility.

### CODE REVIEW

**Comment by sventorben** [comment]
Hello @thorsten-l and thanks for the contribution.

Can you please explain a bit what is the exact use case you are trying to support here?

I am asking, because I do not understand why you need this flexibility. I would say it adds unnecessary complexity and also contradicts the concept of composite roles in Keycloak. 

The `UserModel` inherits from `RoleMapperModel`. The function `RoleMapperModel.hasRole(RoleModel)` that is used here, already handles compsoite role resolution. Please see javadoc [here](https://github.com/keycloak/keycloak/blob/20.0.3/server-spi/src/main/java/org/keycloak/models/RoleMapperModel.java#L69) and implementation [here](https://github.com/keycloak/keycloak/blob/20.0.3/model/map/src/main/java/org/keycloak/models/map/user/MapUserAdapter.java#L312) and [here](https://github.com/keycloak/keycloak/blob/20.0.3/server-spi/src/main/java/org/keycloak/models/utils/RoleUtils.java#L91).

This authenticator is designed to grant permission to access a client. This permission is implicitly associated to the `restricted-access` role. Assuming `restricted-access` is a composite role in your case, why should a role beeing part of this composite inherit that permission? In Keycloak it works the other way around. The composite role (the parent) inherits all permissions from its constituents (the childs). 

Therefore, I tend not to accept this PR at the moment. But feel free to change my mind.

Regards
Sven-Torben

**Comment by thorsten-l** [comment]
Hi @sventorben ,

we have over 100 roles imported from our LDAP into KeyCloak and we wish to use them as associated roles within the 'restricted-access' role. But this does NOT work as expected. I debug the code and neither user.hasDirectRole nor user.hasRole results a 'true' value for members of an associated/composite role. These few lines of code tests explicit the composite roles and now it works as we need it.    incl. false-positive tests ;-)

Ciao
Thorsten

**Comment by sventorben** [comment]
Hello @thorsten-l 

just rephrasing for my understanding:
You import roles from LDAP, for example `role-a` and `role-b`. Then your create a `restricted-access` role as a composite client role. You add `role-a` to the `restricted-access` role and associate `role-a` to a user. 
You expect the user to have access to the client while other user which may be associated to `role-b` or no role at all should be denied access.
Did I get that right?

**Comment by thorsten-l** [comment]
LDAP: About 30000 users are members in over 320 roles.  All roles, users and their role members belongings are imported to keycloak.  This works fine. A 'restricted-access' role is explicit assigned to a specific client and to this 'restricted-access' role are LDAP Roles assigned as associaded roles. In this example all "external moodle users" are allowed to use app1.

Bildschirmfoto 2023-01-25 um 11 12 06

Bildschirmfoto 2023-01-25 um 11 13 02

**Comment by sventorben** [comment]
OK, I understand that use case, but that is not how role inheritance with composite roles work in Keycloak. It is exactly the other way around.

A role basically represents a set of permissions. Let's assume we have 2 permissions `read` and `write` and two roles `Reader` and `Manager`. The `reader` role includes permission `read` and the `Manager` role includes the permission `write`. The `Manager` role is also a composite role and has the role `Reader` associated to it. 
Then a user `User1` that has role `Reader` assigned has effective permissions `read` and a user `User2` has effective permissions  `write` and `read`.

image

With this authenticator the permission of accessing a client is coupled to the role `restricted-access`. Which means for your use case to work your role `external moodle user` would need to be a composite role that has the `restricted-access` role associated to it.

image

This is how composite roles work in Keycloak and inheritance of roles and associated permissions (or attributes) works only in this one direction. Please see [docs for details](https://www.keycloak.org/docs/latest/server_admin/#_composite-roles).

So, I will not be able to incorporate your proposed logic into this authenticator, because it does not align with this general Keycloak principal. Sorry, but I have to keep the authenticator consistent and useable in general and this change could imply unforseen issues or at least not so obvious and unexpected behaviour for other users. 

Maybe you may want to reconsider your role design. Your roles could be composite roles and have the `restricted-access` role associated to it. Or maybe groups could be a better fit instead of roles where each groups has the `restricted-access` role assigned.

Again, sorry. I really appreciate the efforts you put into this.

Regards
Sven-Torben

**Comment by thorsten-l** [comment]
Hi @sventorben 

thank you very much for your details explanation, now i understand the concept. It was no waste of time because i learned a lot ;-)

Ciao
Thorsten

**Pull request closed without merging**
